version: "3"

services:
  app:
    build:
      context: .
    ports:
      # maps server port to docker port
      - "8000:8000"
    volumes:
      # maps local file to docker files, so every change is
      # being reflected automatically
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
